/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum ClientBusinessStructure {
    MULTI_MEMBER_LLC = 'MULTI_MEMBER_LLC',
    SINGLE_MEMBER_LLC = 'SINGLE_MEMBER_LLC',
    NON_PROFIT = 'NON_PROFIT',
    GOVERNMENT_AGENCY = 'GOVERNMENT_AGENCY',
    PRIVATE_CORPORATION = 'PRIVATE_CORPORATION',
    PUBLIC_CORPORATION = 'PUBLIC_CORPORATION',
    PARTNERSHIP = 'PARTNERSHIP',
    SOLE_PROPRIETORSHIP = 'SOLE_PROPRIETORSHIP',
    TRUST = 'TRUST',
    OTHER = 'OTHER',
}
