/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { DynAssetValueCategory } from './DynAssetValueCategory';
import type { LocalDate } from './LocalDate';
import type { UUID } from './UUID';

/**
 * A JSON blob representing a dynamic asset value dividend request.
 */
export type DynamicAssetValueDividendRequest = {
    /**
     * The asset category
     */
    category: DynAssetValueCategory;
    /**
     * The fund account ID
     */
    fundAccountId: UUID;
    /**
     * The counter party ID
     */
    counterPartyId: UUID;
    /**
     * The config label
     */
    label: string;
    /**
     * Notes related to the record
     */
    notes?: string | null;
    /**
     * The transaction currency
     */
    currency: string;
    /**
     * The contract quantity
     */
    amount: number;
    /**
     * The dividend date
     */
    exDivDate: LocalDate;
    /**
     * The market code
     */
    marketCode: string;
    /**
     * The security ISIN
     */
    isin?: string | null;
    /**
     * The security description
     */
    secDesc: string;
    /**
     * The security ID
     */
    secId: string;
    /**
     * The dividend #
     */
    dividendNo?: string | null;
    /**
     * Indicates if the security should be created in the position management module
     */
    createMissingSecurity: boolean;
    /**
     * The reference transaction code. This is usually a code generated by an upstream or used for uploading records
     */
    refCode?: string | null;
    /**
     * The auto approve flag is used to indicate that the transaction should be approved automatically
     */
    autoApprove?: boolean;
};

