/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum AccountHoldType {
    CARD_AUTHORIZATION = 'CARD_AUTHORIZATION',
    OTHERS = 'OTHERS',
    CARD_SETTLEMENT = 'CARD_SETTLEMENT',
    CARD_REVERSAL = 'CARD_REVERSAL',
    CARD_REFUND = 'CARD_REFUND',
    CARD_CHARGEBACK = 'CARD_CHARGEBACK',
    CHECK_AUTHORIZATION = 'CHECK_AUTHORIZATION',
    CHECK_SETTLEMENT = 'CHECK_SETTLEMENT',
    CHECK_REVERSAL = 'CHECK_REVERSAL',
    TRANSFER_AUTHORIZATION = 'TRANSFER_AUTHORIZATION',
}
