/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum LoanProductFeeType {
    MANUAL = 'MANUAL',
    DEDUCTED_FROM_DISBURSEMENT = 'DEDUCTED_FROM_DISBURSEMENT',
    CAPITALIZED_DISBURSEMENT = 'CAPITALIZED_DISBURSEMENT',
    AMORTIZED_WITH_PAYMENTS = 'AMORTIZED_WITH_PAYMENTS',
    UPFRONT_AT_DISBURSEMENT = 'UPFRONT_AT_DISBURSEMENT',
    LATE_PAYMENT = 'LATE_PAYMENT',
}
