/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A JSON blob representing a fixed deposit transaction tranche. The fields marked with an * means that they are required.
 */
export type FixedDepositTransactionTranche = {
    /**
     * The unique ID for the record. This is the ID that is used in all services and related records when referencing the record.
     */
    id: string;
    /**
     * The ID of the user that created the record.
     */
    createdBy: string;
    /**
     * Indicates when the record was created.
     */
    createdAt: string;
    /**
     * The ID of the user that last modified the record.
     */
    updatedBy: string;
    /**
     * Indicates when the record was last modified.
     */
    updatedAt: string;
    /**
     * Indicates if this is a deleted record
     */
    deleted: boolean;
    /**
     * The current status of the order..
     */
    status: FixedDepositTransactionTranche.status;
    /**
     * The transaction type
     */
    transactionType: FixedDepositTransactionTranche.transactionType;
    /**
     * A unique tranche number that is generated by the investing service.
     */
    trancheNo: string;
    /**
     * The principal amount
     */
    principal: number;
    /**
     * The rate used to book the tranche.
     */
    interestRate: number;
    /**
     * The investment start date.
     */
    startDate: string;
    /**
     * The commission calculated for the order
     */
    commission: number;
    /**
     * The fees calculated for the order
     */
    fees: number;
    /**
     * The total amount for the order
     */
    totalAmount: number;
    /**
     * The penalty calculated for the investments withdrawn before maturity
     */
    penalty: number;
    /**
     * The journal ID used to start the transaction
     */
    journalId?: string;
    transactionId: string;
};

export namespace FixedDepositTransactionTranche {

    /**
     * The current status of the order..
     */
    export enum status {
        PENDING = 'PENDING',
        APPROVED = 'APPROVED',
        RUNNING = 'RUNNING',
        ROLLED_OVER = 'ROLLED_OVER',
        TERMINATED = 'TERMINATED',
        MATURED = 'MATURED',
        REVERSED = 'REVERSED',
    }

    /**
     * The transaction type
     */
    export enum transactionType {
        ADDITION = 'ADDITION',
        WITHDRAWAL = 'WITHDRAWAL',
    }


}

