/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A JSON blob representing a settlement holiday. The fields marked with an * means that they are required.
 */
export type Holiday = {
    /**
     * The unique ID for the record. This is the ID that is used in all services and related records when referencing the record.
     */
    id: string;
    /**
     * The ID of the user that created the record.
     */
    createdBy: string;
    /**
     * Indicates when the record was created.
     */
    createdAt: string;
    /**
     * The ID of the user that last modified the record.
     */
    updatedBy: string;
    /**
     * Indicates when the record was last modified.
     */
    updatedAt: string;
    /**
     * Indicates if this is a deleted record
     */
    deleted: boolean;
    /**
     * The status of the branch. See the enumeration for acceptable values.
     */
    status: Holiday.status;
    /**
     * A unique holiday code generated by the system.
     */
    code: string;
    /**
     * The holiday country code
     */
    country: string;
    /**
     * The type of holiday. See the enumeration for acceptable values.
     */
    type: Holiday.type;
    /**
     * The start date for the holiday.
     */
    startDate: string;
    /**
     * The end date for the holiday.
     */
    endDate: string;
    /**
     * A text that describes the holiday
     */
    label: string;
    /**
     * Any notes that apply to this holiday
     */
    notes?: string;
};

export namespace Holiday {

    /**
     * The status of the branch. See the enumeration for acceptable values.
     */
    export enum status {
        INACTIVE = 'INACTIVE',
        ACTIVE = 'ACTIVE',
    }

    /**
     * The type of holiday. See the enumeration for acceptable values.
     */
    export enum type {
        SCHEDULED = 'SCHEDULED',
        ADHOC = 'ADHOC',
    }


}

