/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A JSON blob representing an account. The fields marked with an * means that they are required.
 */
export type InvestmentAccount = {
    /**
     * The unique ID for the record. This is the ID that is used in all services and related records when referencing the record.
     */
    id: string;
    /**
     * The ID of the user that created the record.
     */
    createdBy: string;
    /**
     * Indicates when the record was created.
     */
    createdAt: string;
    /**
     * The ID of the user that last modified the record.
     */
    updatedBy: string;
    /**
     * Indicates when the record was last modified.
     */
    updatedAt: string;
    /**
     * Indicates if this is a deleted record
     */
    deleted: boolean;
    totalValue: number;
    /**
     * A unique identifier for the client that is generated by the crm service and is required when creating a new account.
     */
    clientId: string;
    /**
     * The management type. See the enumeration for acceptable values.
     */
    mgmtType: InvestmentAccount.mgmtType;
    /**
     * The account type. See the enumeration for acceptable values.
     */
    status: InvestmentAccount.status;
    /**
     * The investing type. See the enumeration for acceptable values.
     */
    accountUsage: InvestmentAccount.accountUsage;
    /**
     * Specify a investing account code if applicable and where it has already been setup at the registry.
     */
    tradingAccountNo?: string;
    /**
     * Specify a investing sub account code if applicable and the main investing account code has already been setup at the registry.
     */
    tradingSubAccountNo?: string;
    /**
     * A unique account code that is generated by the investing service.
     */
    accountNo: string;
    /**
     * A text value that describes the account
     */
    accountLabel: string;
    /**
     * A unique client code that is generated by the crm service and is populated by the investing service.
     */
    clientCode?: string;
    /**
     * A label that describes the client and is populated by the investing service.
     */
    clientLabel: string;
    /**
     * Any notes that apply to this account
     */
    notes?: string;
    /**
     * Specify the acceptable leverage for margin investing
     */
    leverage: number;
    /**
     * The currency used for managing the account.
     */
    currency: string;
    /**
     * The cash balance for the account
     */
    cashBalance: number;
    /**
     * Indicates when the balance was updated.
     */
    balanceTime?: string;
    /**
     * Specify the applicable margin rate
     */
    marginInterestRate?: number;
    /**
     * Specify the applicable margin limit
     */
    marginLimit?: number;
    /**
     * Specify the applicable commission rate
     */
    commissionOverride?: number;
    /**
     * A reference code for the account record in an upstream system
     */
    refCode: string;
    /**
     * The date that the account was opened. Defaults to the current date if not provided.
     */
    accountOpenDate: string;
    /**
     * Indicates if the account should be automatically approved
     */
    autoApprove: boolean;
    /**
     * When investing in funds this will determine how dividends will be treated during the distribution process. If CASH is selected the dividend will be posted into the investment account, otherwise it will be reinvested. It will default to UNITS if no value is maintained in the account.
     */
    dividendDistribution?: InvestmentAccount.dividendDistribution;
    /**
     * When this is checked, proceeds from the sale of assets are not deposited into the cash account. The fees and consideration will be settled by the CSD and the client will be invoiced only for the commission. This flag can only be modified for accounts that have been not approved.
     */
    directCashSettlement: boolean;
    /**
     * Specify a clearing account code if applicable and has already been setup at the registry.
     */
    clearingAccountNo?: string;
    /**
     * The maximum open buy limit for this account. Setting this to zero will disable this feature.
     */
    maxOpenBuyLimit?: number;
    /**
     * The maximum daily buy limit for this account. Setting this to zero will disable this feature.
     */
    maxDailyBuyLimit?: number;
    /**
     * The cash interest rate for credit balances. This is used to compute interest for products that pay interest.
     */
    cashInterestRate?: number;
    /**
     * The ID of the custodian attached to the account. This has to map to valid and active custodian in the system.
     */
    custodianId?: string;
    /**
     * The ID of the custodian attached to the account. This has to map to valid and active agent in the system.
     */
    agentId?: string;
    /**
     * The product ID
     */
    productId: string;
    /**
     * The branch code
     */
    branchCode: string;
    /**
     * The branch label
     */
    branchLabel: string;
    /**
     * The branch ID
     */
    branchId: string;
    /**
     * The GL account ID representing the cash liability account
     */
    glAccountId: string;
    /**
     * The product code
     */
    productCode: string;
    /**
     * The product label
     */
    productLabel: string;
    marginAvailable?: boolean;
};

export namespace InvestmentAccount {

    /**
     * The management type. See the enumeration for acceptable values.
     */
    export enum mgmtType {
        SELF = 'SELF',
        ADVISORY = 'ADVISORY',
        MANAGED = 'MANAGED',
        CUSTODIAN = 'CUSTODIAN',
        RESERVED = 'RESERVED',
        PROP = 'PROP',
    }

    /**
     * The account type. See the enumeration for acceptable values.
     */
    export enum status {
        PENDING = 'PENDING',
        ACTIVE = 'ACTIVE',
        OPEN_CLOSING_ONLY = 'OPEN_CLOSING_ONLY',
        SUSPENDED = 'SUSPENDED',
        CLOSED = 'CLOSED',
        NO_DEBITS = 'NO_DEBITS',
    }

    /**
     * The investing type. See the enumeration for acceptable values.
     */
    export enum accountUsage {
        LIVE = 'LIVE',
        PRACTICE = 'PRACTICE',
    }

    /**
     * When investing in funds this will determine how dividends will be treated during the distribution process. If CASH is selected the dividend will be posted into the investment account, otherwise it will be reinvested. It will default to UNITS if no value is maintained in the account.
     */
    export enum dividendDistribution {
        CASH = 'CASH',
        UNITS = 'UNITS',
    }


}

