/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A JSON blob representing a client report record.
 */
export type InvestmentAccountRecordDTO = {
    /**
     * The unique ID for the record. This is the ID that is used in all services and related records when referencing the record.
     */
    id?: string;
    /**
     * A unique identifier for the client that is generated by the crm service and is required when creating a new account.
     */
    clientId?: string;
    /**
     * A unique client code that is generated by the crm service and is populated by the investing service.
     */
    clientCode?: string;
    /**
     * A label that describes the client and is populated by the investing service.
     */
    clientLabel?: string;
    /**
     * The unique system generated client code
     */
    accountNo?: string;
    /**
     * A label for the client record
     */
    accountLabel?: string;
    /**
     * A reference code for the client record in an upstream system
     */
    refCode?: string;
    /**
     * The currency used for managing the account.
     */
    currency?: string;
    /**
     * Specify a investing sub account code if applicable and the main investing account code has already been setup at the registry.
     */
    tradingAccountNo?: string;
    /**
     * The account type. See the enumeration for acceptable values.
     */
    status?: InvestmentAccountRecordDTO.status;
};

export namespace InvestmentAccountRecordDTO {

    /**
     * The account type. See the enumeration for acceptable values.
     */
    export enum status {
        PENDING = 'PENDING',
        ACTIVE = 'ACTIVE',
        OPEN_CLOSING_ONLY = 'OPEN_CLOSING_ONLY',
        SUSPENDED = 'SUSPENDED',
        CLOSED = 'CLOSED',
        NO_DEBITS = 'NO_DEBITS',
    }


}

