/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A JSON blob representing a margin call.
 */
export type MarginCall = {
    /**
     * The unique ID for the record. This is the ID that is used in all services and related records when referencing the record.
     */
    id: string;
    /**
     * The ID of the user that created the record.
     */
    createdBy: string;
    /**
     * Indicates when the record was created.
     */
    createdAt: string;
    /**
     * The ID of the user that last modified the record.
     */
    updatedBy: string;
    /**
     * Indicates when the record was last modified.
     */
    updatedAt: string;
    /**
     * Indicates if this is a deleted record
     */
    deleted: boolean;
    /**
     * The account ID
     */
    accountId?: string;
    /**
     * A unique account code that is generated by the investing service.
     */
    accountNo: string;
    /**
     * A text value that describes the account
     */
    accountLabel: string;
    /**
     * The call #. This is auto generated by the system
     */
    callNo: string;
    /**
     * The description of the call.
     */
    description: string;
    /**
     * The currency used for managing the account.
     */
    currency: string;
    /**
     * The maintenance rate configured on the portfolio
     */
    maintenanceRate?: number;
    /**
     * The current market value of the account
     */
    accountValue?: number;
    /**
     * The current value of the equity in the account
     */
    equityValue?: number;
    /**
     * The margin call value
     */
    callValue?: number;
    /**
     * The date that the margin call was generated
     */
    callDate: string;
    /**
     * The call status
     */
    status: MarginCall.status;
};

export namespace MarginCall {

    /**
     * The call status
     */
    export enum status {
        PENDING = 'PENDING',
        RESOLVED = 'RESOLVED',
    }


}

