/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { WithHoldingTaxSlab } from './WithHoldingTaxSlab';

/**
 * A JSON blob representing a withholding tax. The fields marked with an * means that they are required.When processing a transaction, the withholding is calculated based on the transaction amount.If the rate type is fixed, the default rate is used. If the rate type is tiered, the rate is calculated based on the configured tiers.If a tier is not found, the default rate is used. The fixed amount is added to the calculated value.
 */
export type WithHoldingTax = {
    /**
     * The unique ID for the record. This is the ID that is used in all services and related records when referencing the record.
     */
    id: string;
    /**
     * The ID of the user that created the record.
     */
    createdBy: string;
    /**
     * Indicates when the record was created.
     */
    createdAt: string;
    /**
     * The ID of the user that last modified the record.
     */
    updatedBy: string;
    /**
     * Indicates when the record was last modified.
     */
    updatedAt: string;
    /**
     * Indicates if this is a deleted record
     */
    deleted: boolean;
    /**
     * The status of the rule. See the enumeration for acceptable values.
     */
    status: WithHoldingTax.status;
    /**
     * A unique tax code that is generated by the investing service.
     */
    code: string;
    /**
     * A text that describes the tax
     */
    label: string;
    /**
     * Any notes that apply to this tax
     */
    notes?: string;
    /**
     * The currency for the tax values.
     */
    currency: string;
    /**
     * The start date for the tax
     */
    startDate: string;
    /**
     * The end date for the tax
     */
    endDate: string;
    /**
     * The rate type
     */
    rateType: WithHoldingTax.rateType;
    /**
     * The default rate
     */
    defaultRate: number;
    /**
     * The fixed amount that is added to the calculated value
     */
    fixedAmount: number;
    /**
     * The account ID for accruing the withholding taxes (Liability)
     */
    withholdingTaxAccountId: string;
    /**
     * The account label for the withholding tax (Liability)
     */
    withholdingTaxAccountLabel: string;
    /**
     * The account # for the withholding tax (Liability)
     */
    withholdingTaxAccountNo: string;
    taxSlabs?: Array<WithHoldingTaxSlab>;
};

export namespace WithHoldingTax {

    /**
     * The status of the rule. See the enumeration for acceptable values.
     */
    export enum status {
        ACTIVE = 'ACTIVE',
        INACTIVE = 'INACTIVE',
    }

    /**
     * The rate type
     */
    export enum rateType {
        FIXED = 'FIXED',
        TIERED = 'TIERED',
    }


}

