/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { DynAssetValueCategory } from './DynAssetValueCategory';
import type { DynAssetValueTransactionType } from './DynAssetValueTransactionType';
import type { LocalDate } from './LocalDate';
import type { UUID } from './UUID';

/**
 * A JSON blob representing a dynamic asset value transaction request.
 */
export type DynamicAssetValueTransactionRequest = {
    /**
     * The asset category
     */
    category: DynAssetValueCategory;
    /**
     * The treasury account ID
     */
    treasuryAccountId: UUID;
    /**
     * The counter party ID
     */
    counterPartyId: UUID;
    /**
     * The config label
     */
    label: string;
    /**
     * Notes related to the record
     */
    notes?: string | null;
    /**
     * The transaction currency
     */
    currency: string;
    /**
     * The contract quantity
     */
    quantity: number;
    /**
     * The contract price
     */
    price: number;
    /**
     * The type of transaction
     */
    transactionType: DynAssetValueTransactionType;
    /**
     * The trade date
     */
    tradeDate: LocalDate;
    /**
     * The settlement days
     */
    settlementDays: number;
    /**
     * The custody rate
     */
    custodyFeeRate?: number | null;
    /**
     * The transaction rate
     */
    transactionFeeRate?: number | null;
    /**
     * The transaction fixed charge
     */
    fixedCharge?: number | null;
    /**
     * The market code
     */
    marketCode: string;
    /**
     * The security ISIN
     */
    isin?: string | null;
    /**
     * The security description
     */
    secDesc: string;
    /**
     * The security ID
     */
    secId: string;
    /**
     * The contract #
     */
    contractNo?: string | null;
    /**
     * Indicates if the security should be created in the position management module
     */
    createMissingSecurity: boolean;
    /**
     * The reference transaction code. This is usually a code generated by an upstream or used for uploading records
     */
    refCode?: string | null;
    /**
     * The position transfer date is used to indicate that the asset record was migrated from another system and accruals before this date will not be posted
     */
    positionTransferDate?: LocalDate | null;
    /**
     * The auto approve flag is used to indicate that the transaction should be approved automatically
     */
    autoApprove?: boolean;
};

