/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FixedIncomeCategory } from './FixedIncomeCategory';
import type { FixedIncomeTransactionCouponDateGeneration } from './FixedIncomeTransactionCouponDateGeneration';
import type { FixedIncomeTransactionCouponFrequency } from './FixedIncomeTransactionCouponFrequency';
import type { FixedIncomeTransactionCouponType } from './FixedIncomeTransactionCouponType';
import type { InterestBasis } from './InterestBasis';
import type { LocalDate } from './LocalDate';
import type { UUID } from './UUID';

/**
 * A JSON blob representing a discounted instrument transaction request.
 */
export type FixedIncomeTransactionRequest = {
    /**
     * The asset category
     */
    category: FixedIncomeCategory;
    /**
     * The treasury account ID
     */
    treasuryAccountId: UUID;
    /**
     * The counter party ID
     */
    counterPartyId: UUID;
    /**
     * The config label
     */
    label: string;
    /**
     * Notes related to the record
     */
    notes?: string | null;
    /**
     * The transaction currency
     */
    currency: string;
    /**
     * The face value amount
     */
    faceValue: number;
    /**
     * The coupon frequency
     */
    couponFrequency: FixedIncomeTransactionCouponFrequency;
    /**
     * The coupon type
     */
    couponType: FixedIncomeTransactionCouponType;
    /**
     * The interest basis
     */
    interestBasis: InterestBasis;
    /**
     * The start date
     */
    issueDate: LocalDate;
    /**
     * The maturity date
     */
    maturityDate: LocalDate;
    /**
     * The trade date
     */
    tradeDate: LocalDate;
    /**
     * The settlement days
     */
    settlementDays: number;
    /**
     * The custody rate
     */
    custodyFeeRate?: number | null;
    /**
     * The transaction rate
     */
    transactionFeeRate?: number | null;
    /**
     * The transaction fixed charge
     */
    fixedCharge?: number | null;
    /**
     * The coupon rate generation rule
     */
    couponDateGeneration: FixedIncomeTransactionCouponDateGeneration;
    /**
     * The coupon rate
     */
    couponRate?: number;
    /**
     * The withholding tax rate
     */
    withHoldingTaxRate?: number | null;
    /**
     * The market code
     */
    marketCode: string;
    /**
     * The security description
     */
    secDesc: string;
    /**
     * The security ID
     */
    secId: string;
    /**
     * The security ISIN
     */
    isin?: string | null;
    /**
     * The clean price
     */
    cleanPrice: number;
    /**
     * The contract #
     */
    contractNo?: string | null;
    /**
     * Indicates if the security should be created in the position management module
     */
    createMissingSecurity: boolean;
    /**
     * The reference transaction code. This is usually a code generated by an upstream or used for uploading records
     */
    refCode?: string | null;
    /**
     * The position transfer date is used to indicate that the asset record was migrated from another system and accruals before this date will not be posted
     */
    positionTransferDate?: LocalDate | null;
    /**
     * The auto approve flag is used to indicate that the transaction should be approved automatically
     */
    autoApprove?: boolean;
};

