/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { InterestBasis } from './InterestBasis';
import type { LocalDate } from './LocalDate';
import type { MoneyMarketCategory } from './MoneyMarketCategory';
import type { MoneyMarketTransactionChargeRateType } from './MoneyMarketTransactionChargeRateType';
import type { MoneyMarketTransactionInterestType } from './MoneyMarketTransactionInterestType';
import type { UUID } from './UUID';

/**
 * A JSON blob representing a discounted instrument transaction request.
 */
export type MoneyMarketTransactionRequest = {
    /**
     * The asset category
     */
    category: MoneyMarketCategory;
    /**
     * The treasury account ID
     */
    treasuryAccountId: UUID;
    /**
     * The counter party ID
     */
    counterPartyId: UUID;
    /**
     * The config label
     */
    label: string;
    /**
     * Notes related to the record
     */
    notes?: string | null;
    /**
     * The transaction currency
     */
    currency: string;
    /**
     * The face value amount
     */
    faceValue: number;
    /**
     * The type of interest
     */
    interestType: MoneyMarketTransactionInterestType;
    /**
     * The interest basis
     */
    interestBasis: InterestBasis;
    /**
     * The start date
     */
    startDate: LocalDate;
    /**
     * The maturity date
     */
    maturityDate: LocalDate;
    /**
     * The discount rate
     */
    discountRate: number;
    /**
     * The rate configuration for calculating custody fees
     */
    custodyFeeRateType?: MoneyMarketTransactionChargeRateType | null;
    /**
     * The custody rate
     */
    custodyFeeRate?: number | null;
    /**
     * The rate configuration for calculating transaction fees
     */
    transactionFeeRateType?: MoneyMarketTransactionChargeRateType | null;
    /**
     * The transaction rate
     */
    transactionFeeRate?: number | null;
    /**
     * The transaction fixed charge
     */
    fixedCharge?: number | null;
    /**
     * The contract #
     */
    contractNo?: string | null;
    /**
     * The reference transaction code. This is usually a code generated by an upstream or used for uploading records
     */
    refCode?: string | null;
    /**
     * The position transfer date is used to indicate that the asset record was migrated from another system and accruals before this date will not be posted
     */
    positionTransferDate?: LocalDate | null;
    /**
     * The auto approve flag is used to indicate that the transaction should be approved automatically
     */
    autoApprove?: boolean;
};

