/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum TenantLicenceType {
    TRADING = 'TRADING',
    ASSET_MANAGEMENT = 'ASSET_MANAGEMENT',
    FUNDS_MANAGEMENT = 'FUNDS_MANAGEMENT',
    COMPLIANCE = 'COMPLIANCE',
    GENERAL_LEDGER = 'GENERAL_LEDGER',
    ROBO_ADVISORY = 'ROBO_ADVISORY',
    CLIENT_ENGAGEMENT = 'CLIENT_ENGAGEMENT',
    INSURANCE = 'INSURANCE',
    REGULATORY_REPORTING = 'REGULATORY_REPORTING',
    BANKING = 'BANKING',
}
